# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'invite_member_widget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_invite_member_widget(object):
    def setupUi(self, invite_member_widget):
        invite_member_widget.setObjectName("invite_member_widget")
        invite_member_widget.resize(375, 100)
        self.verticalLayout = QtWidgets.QVBoxLayout(invite_member_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(invite_member_widget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_nickname_label = QtWidgets.QLabel(self.widget)
        self.user_nickname_label.setObjectName("user_nickname_label")
        self.horizontalLayout.addWidget(self.user_nickname_label)
        self.check_btn = QtWidgets.QPushButton(self.widget)
        self.check_btn.setCheckable(True)
        self.check_btn.setObjectName("check_btn")
        self.horizontalLayout.addWidget(self.check_btn)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(invite_member_widget)
        QtCore.QMetaObject.connectSlotsByName(invite_member_widget)

    def retranslateUi(self, invite_member_widget):
        _translate = QtCore.QCoreApplication.translate
        invite_member_widget.setWindowTitle(_translate("invite_member_widget", "Form"))
        self.user_nickname_label.setText(_translate("invite_member_widget", "TextLabel"))
        self.check_btn.setText(_translate("invite_member_widget", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    invite_member_widget = QtWidgets.QWidget()
    ui = Ui_invite_member_widget()
    ui.setupUi(invite_member_widget)
    invite_member_widget.show()
    sys.exit(app.exec_())
