# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_invite_user_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_invite_member_widget(object):
    def setupUi(self, invite_member_widget):
        invite_member_widget.setObjectName("invite_member_widget")
        invite_member_widget.resize(375, 100)
        invite_member_widget.setStyleSheet("#widget {\n"
"    background-color: #DBDFEA;\n"
"    color: #1D5D9B;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"    color: #1D5D9B;\n"
"    font: bold 16pt \"나눔고딕\";\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color:#FFEAD2;\n"
"    color: #1D5D9B;\n"
"    font: bold 12pt \"나눔고딕\";\n"
"    border-radius: 20px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: #8294C4;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#F6F1F1;\n"
"}\n"
"\n"
"QPushButton:pressed, QPushButton:checked{\n"
"    background-color:#E7B10A;\n"
"    color: #F7F1E5;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(invite_member_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(invite_member_widget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.user_nickname_label = QtWidgets.QLabel(self.widget)
        self.user_nickname_label.setObjectName("user_nickname_label")
        self.horizontalLayout.addWidget(self.user_nickname_label)
        self.check_btn = QtWidgets.QPushButton(self.widget)
        self.check_btn.setMinimumSize(QtCore.QSize(60, 60))
        self.check_btn.setMaximumSize(QtCore.QSize(60, 60))
        self.check_btn.setCheckable(True)
        self.check_btn.setObjectName("check_btn")
        self.horizontalLayout.addWidget(self.check_btn)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(invite_member_widget)
        QtCore.QMetaObject.connectSlotsByName(invite_member_widget)

    def retranslateUi(self, invite_member_widget):
        _translate = QtCore.QCoreApplication.translate
        invite_member_widget.setWindowTitle(_translate("invite_member_widget", "Form"))
        self.user_nickname_label.setText(_translate("invite_member_widget", "닉네임(유저아이디)"))
        self.check_btn.setText(_translate("invite_member_widget", "초대"))
from Code.front.ui import my_qrc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    invite_member_widget = QtWidgets.QWidget()
    ui = Ui_invite_member_widget()
    ui.setupUi(invite_member_widget)
    invite_member_widget.show()
    sys.exit(app.exec_())
