# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_make_talk_room_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_make_talk_room_widget(object):
    def setupUi(self, make_talk_room_widget):
        make_talk_room_widget.setObjectName("make_talk_room_widget")
        make_talk_room_widget.resize(556, 420)
        make_talk_room_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(212, 212, 212);\n"
"}")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(make_talk_room_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(make_talk_room_widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.widget_3 = QtWidgets.QWidget()
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 458, 310))
        self.widget_3.setObjectName("widget_3")
        self.layout = QtWidgets.QVBoxLayout(self.widget_3)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setSpacing(0)
        self.layout.setObjectName("layout")
        self.invite_member_choice = QtWidgets.QWidget(self.widget_3)
        self.invite_member_choice.setObjectName("invite_member_choice")
        self.invite_member_choice_layout = QtWidgets.QVBoxLayout(self.invite_member_choice)
        self.invite_member_choice_layout.setObjectName("invite_member_choice_layout")
        self.layout.addWidget(self.invite_member_choice)
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 273, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.layout.addWidget(self.widget_2)
        self.scrollArea.setWidget(self.widget_3)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(make_talk_room_widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setMinimumSize(QtCore.QSize(276, 76))
        self.widget.setMaximumSize(QtCore.QSize(276, 76))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout_3.addWidget(self.widget)
        self.decision_btn = QtWidgets.QPushButton(self.frame_2)
        self.decision_btn.setObjectName("decision_btn")
        self.horizontalLayout_3.addWidget(self.decision_btn)
        self.close_btn = QtWidgets.QPushButton(self.frame_2)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_3.addWidget(self.close_btn)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.retranslateUi(make_talk_room_widget)
        QtCore.QMetaObject.connectSlotsByName(make_talk_room_widget)

    def retranslateUi(self, make_talk_room_widget):
        _translate = QtCore.QCoreApplication.translate
        make_talk_room_widget.setWindowTitle(_translate("make_talk_room_widget", "Form"))
        self.label.setText(_translate("make_talk_room_widget", "TextLabel"))
        self.label_2.setText(_translate("make_talk_room_widget", "TextLabel"))
        self.decision_btn.setText(_translate("make_talk_room_widget", "확인"))
        self.close_btn.setText(_translate("make_talk_room_widget", "취소"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    make_talk_room_widget = QtWidgets.QWidget()
    ui = Ui_make_talk_room_widget()
    ui.setupUi(make_talk_room_widget)
    make_talk_room_widget.show()
    sys.exit(app.exec_())
