# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_join_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_join_widget(object):
    def setupUi(self, join_widget):
        join_widget.setObjectName("join_widget")
        join_widget.resize(619, 520)
        join_widget.setStyleSheet("#join_widget{\n"
"    background-color: #1D5D9B\n"
"}\n"
"\n"
"QLabel{\n"
"    color: #FBEEAC;\n"
"    font: bold 16pt \"나눔고딕\";\n"
"}\n"
"\n"
"#label{\n"
"    font: bold 20pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color:#F4D160;\n"
"    color: #1D5D9B;\n"
"    font: bold 12pt \"나눔고딕\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#FFFF9D;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:#FEF5AC;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    color: #1D5D9B;\n"
"    font: bold 12pt \"나눔고딕\";\n"
"}\n"
"\n"
"#input_widget,\n"
"#input_widget_2{\n"
"    background-color : #75C2F6;\n"
"}\n"
"\n"
"\n"
"#input_widget QLabel,\n"
"#input_widget_2 QLabel{\n"
"    color: #1D5D9B;\n"
"}\n"
"\n"
"#input_widget #label_id_message,\n"
"#input_widget #label_join_warning\n"
"{\n"
"    color: #F2D7D9\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(join_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_title = QtWidgets.QFrame(join_widget)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(230, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.btn_flist_close = QtWidgets.QPushButton(self.frame_title)
        self.btn_flist_close.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_flist_close.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_flist_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_flist_close.setIcon(icon)
        self.btn_flist_close.setObjectName("btn_flist_close")
        self.horizontalLayout_8.addWidget(self.btn_flist_close)
        self.verticalLayout.addWidget(self.frame_title)
        self.widget = QtWidgets.QWidget(join_widget)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(join_widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 20))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout.addWidget(self.widget_2)
        self.input_widget = QtWidgets.QWidget(join_widget)
        self.input_widget.setMinimumSize(QtCore.QSize(0, 40))
        self.input_widget.setObjectName("input_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.input_widget)
        self.verticalLayout_2.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_6 = QtWidgets.QWidget(self.input_widget)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.widget_6)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setMaximumSize(QtCore.QSize(100, 30))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit_join_id_1 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_join_id_1.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_join_id_1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_join_id_1.setObjectName("lineEdit_join_id_1")
        self.horizontalLayout.addWidget(self.lineEdit_join_id_1)
        self.btn_join_duplicatecheck = QtWidgets.QPushButton(self.widget_6)
        self.btn_join_duplicatecheck.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_join_duplicatecheck.setMaximumSize(QtCore.QSize(16777215, 20))
        self.btn_join_duplicatecheck.setObjectName("btn_join_duplicatecheck")
        self.horizontalLayout.addWidget(self.btn_join_duplicatecheck)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.widget_join_warning = QtWidgets.QWidget(self.input_widget)
        self.widget_join_warning.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_join_warning.setObjectName("widget_join_warning")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_join_warning)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(130, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.label_id_message = QtWidgets.QLabel(self.widget_join_warning)
        self.label_id_message.setMinimumSize(QtCore.QSize(0, 30))
        self.label_id_message.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_id_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id_message.setObjectName("label_id_message")
        self.horizontalLayout_5.addWidget(self.label_id_message)
        spacerItem4 = QtWidgets.QSpacerItem(309, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.widget_join_warning)
        self.widget_7 = QtWidgets.QWidget(self.input_widget)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.lineedit_join_pw = QtWidgets.QLineEdit(self.widget_7)
        self.lineedit_join_pw.setObjectName("lineedit_join_pw")
        self.horizontalLayout_2.addWidget(self.lineedit_join_pw)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.input_widget)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.label_8 = QtWidgets.QLabel(self.widget_8)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.lineedit_join_pw_2 = QtWidgets.QLineEdit(self.widget_8)
        self.lineedit_join_pw_2.setObjectName("lineedit_join_pw_2")
        self.horizontalLayout_3.addWidget(self.lineedit_join_pw_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.input_widget)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(85, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.label_6 = QtWidgets.QLabel(self.widget_9)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setMaximumSize(QtCore.QSize(100, 30))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineedit_join_user_name = QtWidgets.QLineEdit(self.widget_9)
        self.lineedit_join_user_name.setObjectName("lineedit_join_user_name")
        self.horizontalLayout_4.addWidget(self.lineedit_join_user_name)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.verticalLayout_2.addWidget(self.widget_9)
        self.widget_join_warning_2 = QtWidgets.QWidget(self.input_widget)
        self.widget_join_warning_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_join_warning_2.setObjectName("widget_join_warning_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_join_warning_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem11 = QtWidgets.QSpacerItem(130, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.label_join_warning = QtWidgets.QLabel(self.widget_join_warning_2)
        self.label_join_warning.setMinimumSize(QtCore.QSize(0, 30))
        self.label_join_warning.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_join_warning.setAlignment(QtCore.Qt.AlignCenter)
        self.label_join_warning.setObjectName("label_join_warning")
        self.horizontalLayout_10.addWidget(self.label_join_warning)
        spacerItem12 = QtWidgets.QSpacerItem(309, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.verticalLayout_2.addWidget(self.widget_join_warning_2)
        self.verticalLayout.addWidget(self.input_widget)
        self.input_widget_2 = QtWidgets.QWidget(join_widget)
        self.input_widget_2.setMinimumSize(QtCore.QSize(0, 40))
        self.input_widget_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.input_widget_2.setObjectName("input_widget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.input_widget_2)
        self.horizontalLayout_7.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem13 = QtWidgets.QSpacerItem(194, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.btn_join_register = QtWidgets.QPushButton(self.input_widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_join_register.sizePolicy().hasHeightForWidth())
        self.btn_join_register.setSizePolicy(sizePolicy)
        self.btn_join_register.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_join_register.setCheckable(False)
        self.btn_join_register.setObjectName("btn_join_register")
        self.horizontalLayout_7.addWidget(self.btn_join_register)
        self.btn_join_cancel = QtWidgets.QPushButton(self.input_widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_join_cancel.sizePolicy().hasHeightForWidth())
        self.btn_join_cancel.setSizePolicy(sizePolicy)
        self.btn_join_cancel.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_join_cancel.setObjectName("btn_join_cancel")
        self.horizontalLayout_7.addWidget(self.btn_join_cancel)
        spacerItem14 = QtWidgets.QSpacerItem(193, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.verticalLayout.addWidget(self.input_widget_2)
        self.widget_3 = QtWidgets.QWidget(join_widget)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(join_widget)
        QtCore.QMetaObject.connectSlotsByName(join_widget)

    def retranslateUi(self, join_widget):
        _translate = QtCore.QCoreApplication.translate
        join_widget.setWindowTitle(_translate("join_widget", "Form"))
        self.label.setText(_translate("join_widget", "회원가입"))
        self.label_5.setText(_translate("join_widget", "ID:"))
        self.btn_join_duplicatecheck.setText(_translate("join_widget", "중복확인"))
        self.label_id_message.setText(_translate("join_widget", "TextLabel"))
        self.label_7.setText(_translate("join_widget", "비밀번호 입력:"))
        self.label_8.setText(_translate("join_widget", "비밀번호 확인:"))
        self.label_6.setText(_translate("join_widget", "닉네임:"))
        self.label_join_warning.setText(_translate("join_widget", "TextLabel"))
        self.btn_join_register.setText(_translate("join_widget", "회원 등록"))
        self.btn_join_cancel.setText(_translate("join_widget", "취소"))
from Code.front.ui import my_qrc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    join_widget = QtWidgets.QWidget()
    ui = Ui_join_widget()
    ui.setupUi(join_widget)
    join_widget.show()
    sys.exit(app.exec_())
