# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_search_talk_room_member_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_takl_room_member_widget(object):
    def setupUi(self, takl_room_member_widget):
        takl_room_member_widget.setObjectName("takl_room_member_widget")
        takl_room_member_widget.resize(573, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(takl_room_member_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(takl_room_member_widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(449, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea = QtWidgets.QScrollArea(takl_room_member_widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 551, 229))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(takl_room_member_widget)
        QtCore.QMetaObject.connectSlotsByName(takl_room_member_widget)

    def retranslateUi(self, takl_room_member_widget):
        _translate = QtCore.QCoreApplication.translate
        takl_room_member_widget.setWindowTitle(_translate("takl_room_member_widget", "Form"))
        self.pushButton.setText(_translate("takl_room_member_widget", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    takl_room_member_widget = QtWidgets.QWidget()
    ui = Ui_takl_room_member_widget()
    ui.setupUi(takl_room_member_widget)
    takl_room_member_widget.show()
    sys.exit(app.exec_())
