# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_talk_room_member_plus.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_takl_room_member_plus_widget(object):
    def setupUi(self, takl_room_member_plus_widget):
        takl_room_member_plus_widget.setObjectName("takl_room_member_plus_widget")
        takl_room_member_plus_widget.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(takl_room_member_plus_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(takl_room_member_plus_widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.frame_3)
        self.scrollArea = QtWidgets.QScrollArea(takl_room_member_plus_widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 378, 180))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.frame_2 = QtWidgets.QFrame(takl_room_member_plus_widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(takl_room_member_plus_widget)
        QtCore.QMetaObject.connectSlotsByName(takl_room_member_plus_widget)

    def retranslateUi(self, takl_room_member_plus_widget):
        _translate = QtCore.QCoreApplication.translate
        takl_room_member_plus_widget.setWindowTitle(_translate("takl_room_member_plus_widget", "Form"))
        self.pushButton_4.setText(_translate("takl_room_member_plus_widget", "검색"))
        self.pushButton_2.setText(_translate("takl_room_member_plus_widget", "확인"))
        self.pushButton_3.setText(_translate("takl_room_member_plus_widget", "취소"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    takl_room_member_plus_widget = QtWidgets.QWidget()
    ui = Ui_takl_room_member_plus_widget()
    ui.setupUi(takl_room_member_plus_widget)
    takl_room_member_plus_widget.show()
    sys.exit(app.exec_())
